/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/common/AppFooter.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InnerNavbar: typeof import('./components/common/InnerNavbar.vue')['default']
    Navbar: typeof import('./components/common/Navbar.vue')['default']
    Navbar1: typeof import('./components/common/Navbar1.vue')['default']
    Navbar2: typeof import('./components/common/Navbar2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
